version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  hexo_deploy:
    executor:
      name: node/default
      tag: "20.10.0"
    steps:
      - checkout:
          submodules: true # This is the key line!
      - run:
          name: Install pnpm
          command: npm install -g pnpm
      - node/install-packages:
          pkg-manager: pnpm
      - run:
          name: Install Hexo CLI
          command: npm install -g hexo-cli
      - run:
          name: Clean public folder
          command: rm -rf public
      - run:
          name: Generate Hexo Site
          command: hexo generate
      - run:
          name: Install gh-pages package
          command: npm install gh-pages --save-dev
      - run:
          name: Configure Git
          command: |
            git config --global user.email "ci-build@circleci.com"
            git config --global user.name "CircleCI Build"
      - run:
          name: Deploy to GitHub Pages
          command: |
            npx gh-pages -d public -b gh-pages -m "Build generated [skip ci]"
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - hexo_deploy:
          filters:
            branches:
              only:
                - master
